daftbot/routes/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from daftbot.models import User

class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], render_kw={'readonly': True})
    email = StringField('Email', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=255)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')


class SearchForm(FlaskForm):
    q = StringField('Search', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

daftbot/routes/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from daftbot.routes.api import routes

daftbot/routes/api/routes.py
from flask import current_app
from daftbot.routes.api import bp
from daftbot.email import send_email

from flask import jsonify, request, url_for


@bp.route('/celery_status', methods=['GET'])
def celery_status():
    from daftbot import celery
    # from daftbot import db
    ret = []
    i = celery.control.inspect()

    return jsonify({
        'i.scheduled()': i.scheduled(),
        'i.active()': i.active(),
        'i.reserved()': i.reserved(),
    })


@bp.route('/getweb', methods=['GET'])
def getweb():
    import requests
    r = requests.get('https://api.exchangeratesapi.io/latest?base=BRL',)
    return jsonify(r.json())


from daftbot.scripts.startdb import add_users_bot


@bp.route('/add_users', methods=['GET'])
def add_users():
    _data = str(add_users_bot.delay())
    return jsonify({'process': 'done', 'data': _data})


from daftbot.scripts.startdb import add_routes
from daftbot.scripts.celery import update_celery_task


@bp.route('/startdb', methods=['GET'])
def startdb():
    _data_add_users_bot = add_users_bot.delay()
    _data_add_routes = add_routes.delay()
    return jsonify({
        'process': 'done',
        'add_users_bot': str(_data_add_users_bot),
        'add_routes': str(_data_add_routes),
    })


from daftbot.scripts.listings import get_sharing_listings
from daftbot.scripts.daft2db import daft2db
from daftbot.scripts.listings import loop_new_listings
import pickle


@bp.route('/loop_daft', methods=['GET'])
def loop_daft():
    ret = []
    ret = loop_new_listings(max_listing_pages=999999)
    return jsonify({'code': ret})


from daftbot.scripts.listings import loop_xml_listings


@bp.route('/loop_xmls', methods=['GET'])
def loop_xmls():
    ret = []
    ret = loop_xml_listings()
    return jsonify({'code': ret})


from daftbot.scripts import here


@bp.route('/loop_here', methods=['GET'])
def loop_here():
    ret = []
    ret = here.loop_here()
    return jsonify({'code': ret})


from daftbot.scripts.download_images import loop_images


@bp.route('/download_images', methods=['GET'])
def download_images():
    ret = []
    ret = loop_images()
    return jsonify({'code': ret})

from daftbot.scripts.telegram import loop_telegram
@bp.route('/send_telegram', methods=['GET'])
def send_telegram():

    ret = []
    ret = loop_telegram()
    return jsonify({'code': ret})

daftbot/routes/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from daftbot.routes.main import routes

daftbot/routes/main/routes.py
from flask import (
    render_template, flash, redirect, url_for, request, g, current_app
)
from flask_login import current_user, login_required
from datetime import datetime

from daftbot import db
from daftbot.models import User, Listing
from daftbot.routes.main.forms import EditProfileForm, SearchForm
from daftbot.routes.main import bp


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.commit()
        g.search_form = SearchForm()


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html', title='Home')


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'}
    ]
    return render_template('user/user.html', user=user, posts=posts)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me
    return render_template('user/edit_profile.html', title='Edit Profile',
                           form=form)


@bp.route('/search')
@login_required
def search():
    return render_template('search.html', title='Search')
#     if not g.search_form.validate():
#         return redirect(url_for('main.explore'))
#     page = request.args.get('page', 1, type=int)
#     posts, total = Post.search(g.search_form.q.data, page,
#                                current_app.config['POSTS_PER_PAGE'])
#     next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
#         if total > page * current_app.config['POSTS_PER_PAGE'] else None
#     prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
#         if page > 1 else None
#     return render_template('search.html', title=_('Search'), posts=posts,
#                            next_url=next_url, prev_url=prev_url)


@bp.route('/listings')
@login_required
def listings():
    page = request.args.get('page', 1, type=int)
    listings = db.session.query(
        Listing
    ).order_by(
        Listing.date_insert_update.desc()
    ).order_by(
        Listing.source_xml_pub_date.desc().nullslast()
    ).paginate(
        page, current_app.config['LISTINGS_PER_PAGE'], False)


    next_url = url_for('main.listings', page=listings.next_num) \
        if listings.has_next else None

    prev_url = url_for('main.listings', page=listings.prev_num) \
        if listings.has_prev else None

    return render_template('main/listings.html',
                           listings=listings.items,
                           next_url=next_url,
                           prev_url=prev_url)



@bp.route('/api')
def api():

    return render_template('main/api.html',)

daftbot/templates/main/_listing.html
<div class="row">
    <div class="col-md-4">
        {{ listing.raw_dwelling_type }}
    </div>
    <div class="col-md-8">
        <a href="{{ listing.shortcode }}">{{ listing.raw_address_full }}</a>
    </div>
</div>


<div class="row">
    <div class="col-md-2">
        €{{ listing.price }}
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
    <div class="col-md-6">
        {% if listing.routes_to_indeed is iterable %}
        {% for route in listing.routes_to_indeed if route.less_wl%}
        {% if loop.index <= 1 -%} <i class="fas fa-sigma"></i>
            {{ route.total_length|round(1, 'floor') }}km
            (<i class="fas fa-clock"></i>{{route.total_travel_time|round }}min)
            <i class="fas fa-walking"></i>
            {{ route.walking_length|round(1, 'floor') }}km
            (<i class="fas fa-clock"></i>{{route.walking_travel_time|round }}min)

            <i class="fab fa-contao"></i>{{ route.lines_count|round }}
            <i class="fas fa-bus"></i>{{ route.lines_names_concat }}

            {%endif%}
            {% endfor %}
            {%endif%}
    </div>
    <div class="col-md-2">
        {{ listing.views }} views
    </div>
</div>



<div class="row">
    <div class="col-md-2">
        <i class="fas fa-city"></i> {{ listing.city_center_distance }}km
    </div>
    <div class="col-md-2">
        <i class="fas fa-briefcase"></i> {{ listing.indeed_distance }}km
    </div>

    <div class="col-md-6">
        {% if listing.routes_to_indeed is iterable %}
        {% for route in listing.routes_to_indeed if route.less_tl%}
        {% if loop.index <= 1 -%} <i class="fas fa-sigma"></i>

            {{ route.total_length|round(1, 'floor') }}km
            (<i class="fas fa-clock"></i> {{route.total_travel_time|round }}min)
            <i class="fas fa-walking"></i>
            {{ route.walking_length|round(1, 'floor') }}km
            (<i class="fas fa-clock"></i> {{route.walking_travel_time|round }}min)

            <i class="fab fa-contao"></i> {{ route.lines_count|round }}
            <i class="fas fa-bus"></i> {{ route.lines_names_concat }}

            {%endif%}
            {% endfor %}
            {%endif%}
    </div>
    <div class="col-md-2">
        {%if listing.source_xml_pub_date%}
        {{ listing.source_xml_pub_date }}
        {%else%}
        {{ listing.date_insert_update }}
        {%endif%}
    </div>
</div>

<div class="row">
    <div class="col-md-12">&nbsp;
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ul id="tabsJustified" class="nav nav-tabs">
            <li class="nav-item"><a href="" data-target="#images-{{ listing.id }}" data-toggle="tab" class="nav-link small text-uppercase active">Images</a></li>
            <li class="nav-item"><a href="" data-target="#desc-{{ listing.id }}" data-toggle="tab" class="nav-link small text-uppercase">Description</a></li>
            <li class="nav-item"><a href="" data-target="#overv-{{ listing.id }}" data-toggle="tab" class="nav-link small text-uppercase">Overview</a></li>
            <li class="nav-item"><a href="" data-target="#routes-{{ listing.id }}" data-toggle="tab" class="nav-link small text-uppercase">Routes</a></li>
            <li class="nav-item"><a href="" data-target="#ia-{{ listing.id }}" data-toggle="tab" class="nav-link small text-uppercase">IA</a></li>
        </ul>
        <br>
        <div id="tabsJustifiedContent" class="tab-content">
            <div id="images-{{ listing.id }}" class="tab-pane fade active show">
                <div class="col-md-12">
                    <div class="row gallery-block compact-gallery">
                        <div class="row no-gutters">
                            {% for image in listing.images %}
                            <div class="col-md-3 col-lg-3 item zoom-on-hover">
                                <a class="lightbox" href="{{ image.filepath }}">
                                    <img style="max-height: 200px;" class="center image img-thumbnail" src="{{ image.tbfilepath }}">
                                    <span class="description">
                                        <span class="description-heading">heading</span>
                                        <span class="description-body">{{ image.tbfilepath }}

                                        </span>
                                    </span>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div id="desc-{{ listing.id }}" class="tab-pane fade">
                <div class="col-md-12">
                    <h1> Description </h1>
                    <pre style='font-size: 11px;'>
                                {{- listing.description.description -}}

                        </pre>
                </div>
            </div>
            <div id="overv-{{ listing.id }}" class="tab-pane fade">
                <div class="col-md-12">
                    <h1> Overview </h1>
                    {% if listing.overviews is iterable %}
                    {% for over in listing.overviews%}
                    <div class="row">
                        <div class="col-md-6">

                            * {{ over.name }}

                        </div>
                        <div class="col-md-6">
                        </div>
                    </div>
                    {% endfor %}
                    {%endif%}
                </div>
            </div>
            <div id="routes-{{ listing.id }}" class="tab-pane fade">
                <div class="col-md-12">
                    <h1> Routes </h1>
                    {% if listing.routes_to_indeed is iterable %}
                    {% for route in listing.routes_to_indeed%}
                    <div class="row">
                        <div class="col-md-2">
                            <i class="fas fa-sigma"></i>

                            {{ route.total_length|round(1, 'floor') }}km
                            (<i class="fas fa-clock"></i> {{route.total_travel_time|round }}min)
                        </div>
                        <div class="col-md-2">
                            <i class="fas fa-walking"></i>
                            {{ route.walking_length|round(1, 'floor') }}km
                            (<i class="fas fa-clock"></i> {{route.walking_travel_time|round }}min)
                        </div>
                        <div class="col-md-8">
                            <i class="fas fa-bus"></i> {{ route.lines_count|round }}
                            <i class="fas fa-bus"></i> {{ route.lines_names_concat }}

                        </div>
                    </div>
                    {% endfor %}
                    {%endif%}
                </div>
            </div>
            <div id="ia-{{ listing.id }}" class="tab-pane fade">
                <div class="col-md-12">
                    <h1> IA </h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <hr />
    </div>
</div>

daftbot/templates/main/api.html
{% extends 'base.html' %}

{% block app_content %}
<h1>API's</h1>
<div class="row">
    &nbsp;
</div>
<div class="row links">
    <div class="col-md-3">
        <button type="button" class="btn btn-outline-primary">
            <a href="{{ url_for('api.add_users') }}" style="color:inherit">
                Add Users
            </a>
        </button>
    </div>
    <div class="col-md-3">
        <button type="button" class="btn btn-outline-primary">
            <a href="{{ url_for('api.startdb') }}" style="color:inherit">
                Start DB
            </a>
        </button>
    </div>
    <div class="col-md-3">
        <button type="button" class="btn btn-outline-primary">
            <a href="{{ url_for('api.loop_xmls') }}" style="color:inherit">
                Loop XML's
            </a>
        </button>
    </div>
    <div class="col-md-3">
        <button type="button" class="btn btn-outline-primary">
            <a href="{{ url_for('api.loop_here') }}" style="color:inherit">
                Loop Here
            </a>
        </button>
    </div>
</div>
<div class="row">
    &nbsp;
</div>
<div class="row links">
        <div class="col-md-3">
            <button type="button" class="btn btn-outline-primary">
                <a href="{{ url_for('api.download_images') }}" style="color:inherit">
                    Download Images
                </a>
            </button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-outline-primary">
                <a href="{{ url_for('api.loop_daft') }}" style="color:inherit">
                    Loop Daft
                </a>
            </button>
        </div>
</div>
<div class="row">
    <div class="col-md-12" id="pageLoad">
    </div>
</div>

{% endblock %}


{% block scripts %}
{{ super() }}
<script type="text/javascript">
    $(".links a").click(function () {
        $("#pageLoad").load(this.href);

        return false;
    });
</script>
{% endblock %}

daftbot/templates/main/listings.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}



<h1> Hi, {{ current_user.username }}</h1>
{% for listing in listings %}
{% include 'main/_listing.html' %}
{% endfor %}
    <ul class="pagination float-right">
        <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
            <a href="{{ prev_url or '#' }}" class="page-link">
                <span aria-hidden="true">&larr;</span>Newer listings
            </a>
        </li>
        <li class="page-item next{% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}" class="page-link">
                Older listings <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
<style>
    .gallery-block {
        padding-bottom: 10px;
        padding-top: 20px;
    }

    .gallery-block .heading {
        margin-bottom: 50px;
        text-align: center;
    }

    .gallery-block .heading h2 {
        font-weight: bold;
        font-size: 1.4rem;
        text-transform: uppercase;
    }

    .gallery-block.compact-gallery .item {
        overflow: hidden;
        margin-bottom: 0;
        <!-- background: black; -->
        opacity: 1;
    }

    .gallery-block.compact-gallery .item .image {
        transition: 0.8s ease;
    }

    .gallery-block.compact-gallery .item .info {
        position: relative;
        display: inline-block;
    }

    .gallery-block.compact-gallery .item .description {
        display: grid;
        position: absolute;
        bottom: 0;
        left: 0;
        color: #fff;
        padding: 10px;
        font-size: 17px;
        line-height: 18px;
        width: 100%;
        padding-top: 15px;
        padding-bottom: 15px;
        opacity: 1;
        color: #fff;
        transition: 0.8s ease;
        text-align: center;
        text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.2);
        background: linear-gradient(to bottom, transparent, rgba(0, 0, 0, 0.39));
    }

    .gallery-block.compact-gallery .item .description .description-heading {
        font-size: 1em;
        font-weight: bold;
    }

    .gallery-block.compact-gallery .item .description .description-body {
        font-size: 0.8em;
        margin-top: 10px;
        font-weight: 300;
    }

    @media (min-width: 576px) {

        .gallery-block.compact-gallery .item .description {
            opacity: 0;
        }

        .gallery-block.compact-gallery .item a:hover .description {
            opacity: 1;
        }

        .gallery-block .zoom-on-hover:hover .image {
            transform: scale(1.3);
            opacity: 0.7;
        }
    }
</style>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.compact-gallery', { animation: 'slideIn' });
</script>{% endblock %}